/*Script para creación de tablas relacionados con integración*/

/*Tabla que almacena la autenticación contra el servicio web*/
CREATE TABLE INT_AUTH
   ("ID_AUTH" NUMBER,
	"SHORTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"AUTHCODE" VARCHAR2(4 BYTE) NOT NULL ENABLE,
	"ACTIVE" VARCHAR2(1 BYTE),
	"ENDPOINT" VARCHAR2(100 BYTE),
	 CONSTRAINT "INT_AUTH_CON_UNIQUE" UNIQUE ("ACTIVE"));

/*Tabla que almacena el monto disponible por cada línea de costo, tanto para proyectos PC como FM*/
CREATE TABLE "EBS_UNIFIER"."INT_BP_AMOUNT"
   ("ID_BP_AMOUNT" NUMBER,
	"PROJECT_BPA" VARCHAR2(50 BYTE),
	"BITEMID_CS" VARCHAR2(250 BYTE),
	"AMOUNT_BPA" NUMBER,
	"STATUS_BPA" VARCHAR2(10 BYTE),
	"FLAG_EBS" VARCHAR2(1 BYTE),
	"PROJECTUNIFIER" VARCHAR2(30 BYTE),
	"EFFECTIVE_YEAR" NUMBER,
	"EFFECTIVE_DATE" DATE,
	 CONSTRAINT "INT_BP_AMOUNT_PK" PRIMARY KEY ("ID_BP_AMOUNT"));

/*Tabla que almacena los procesos de negocio que han sido procesados*/
CREATE TABLE "EBS_UNIFIER"."INT_BP_PROCESS"
   ("ID_BP_PROCESS" NUMBER,
	"ID_AUTH" NUMBER,
	"BITEMID" VARCHAR2(2000 BYTE),
	"DESCRIPTION" VARCHAR2(500 BYTE),
	"TRANSACTION_EBS" VARCHAR2(100 BYTE),
	"AMOUNT" NUMBER,
	"ID_BP_PROJECT" NUMBER,
	"INT_SOURCE" VARCHAR2(50 BYTE),
	"PROJECT_EBS" VARCHAR2(255 BYTE),
	 CONSTRAINT "INT_BP_PROCESS_PK" PRIMARY KEY ("ID_BP_PROCESS"));

/*Tabla que almacena la relación de proyectos con procesos de negocio*/
CREATE TABLE "EBS_UNIFIER"."INT_BP_PROJECT"
   (	"ID_BP_PROJECT" NUMBER,
	"PROJECT_CODE" VARCHAR2(15 BYTE),
	"BPNAME" VARCHAR2(100 BYTE),
	"ID_INTERFACES" NUMBER,
	"BP_ACTIVE" VARCHAR2(2 BYTE),
	"ID_BP" NUMBER,
	 CONSTRAINT "INT_BP_PROJECT_CON" UNIQUE ("PROJECT_CODE", "BPNAME", "ID_INTERFACES"));

  /*Tabla que almacena las estructura de hojas de costos, de los diferentes proyecto*/
  CREATE TABLE "EBS_UNIFIER"."INT_COST_SHEET"
   (	"ID_COST_SHEET" NUMBER,
	"PROJECT_CS" VARCHAR2(15 BYTE),
	"WBSCODE_CS" VARCHAR2(50 BYTE),
	"WBSITEM_CS" VARCHAR2(150 BYTE),
	"COSTTYPE_CS" VARCHAR2(10 BYTE),
	"STATUS_CS" VARCHAR2(10 BYTE),
	"WBSCODEID_CS" VARCHAR2(50 BYTE),
	"PARENTID_CS" NUMBER,
	"INDENTLEVEL_CS" NUMBER,
	"ORDERID_CS" NUMBER,
	"BITEMID_CS" VARCHAR2(2000 BYTE),
	"IMPTBLE_CS" NUMBER,
	"FLAG_EBS" VARCHAR2(1 BYTE),
	"UNIFIERPROJECT" VARCHAR2(30 BYTE),
	"ACCOUNTING_ACCOUNT" VARCHAR2(100 BYTE),
	 CONSTRAINT "INT_COST_SHEET_PK" PRIMARY KEY ("ID_COST_SHEET"));

  /*Tabla que almacena la información proveniente del ERP EBS*/
  CREATE TABLE "EBS_UNIFIER"."INT_EBS_AMOUNT"
   (	"ID_EBS" NUMBER,
	"PROJECT_EBS" VARCHAR2(250 BYTE) NOT NULL ENABLE,
	"BITEMID_EBS" VARCHAR2(2000 BYTE) NOT NULL ENABLE,
	"AMOUNT_EBS" NUMBER NOT NULL ENABLE,
	"INT_SOURCE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"INT_BATCH_ID" VARCHAR2(20 BYTE),
	"INT_SOURCE_DESC" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
	"TRANSACTION_EBS" VARCHAR2(100 BYTE),
	"LAST_ITEM_EBS" VARCHAR2(3 BYTE),
	"FROM_DATE" DATE,
	"TO_DATE" DATE,
	 CONSTRAINT "INT_EBS_AMOUNT_PK" PRIMARY KEY ("ID_EBS"));

   /*Tabla que almacena las tazas de cambio provenientes de EBS*/
   CREATE TABLE "EBS_UNIFIER"."INT_EXCHANGE_RATES"
    (	"ID_EXCHANGE_RATES" NUMBER,
 	"SOURCE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
 	"FROM_COD_CURRENCY" VARCHAR2(10 BYTE),
 	"TO_COD_CURRENCY" VARCHAR2(10 BYTE) NOT NULL ENABLE,
 	"CONVERSION_DATE" DATE,
 	"CONVERSION_TYPE" VARCHAR2(15 BYTE),
 	"CONVERSION_RATE" NUMBER NOT NULL ENABLE,
 	"INVERSE_CONVERSION_RATE" NUMBER,
 	"TRX_FORMAT" TIMESTAMP (6),
 	 CONSTRAINT "INT_EXCHANGE_RATES_PK" PRIMARY KEY ("ID_EXCHANGE_RATES"));

   /*Tabla que almacena la lista de interfaces de integración*/
   CREATE TABLE "EBS_UNIFIER"."INT_INTERFACES"
   (	"ID_INTERFACES" NUMBER,
	"NAME_INTERFACES" VARCHAR2(30 BYTE),
	"DESCRIPTION_INTERFACES" VARCHAR2(500 BYTE),
	 CONSTRAINT "INT_INTERFACES_PK" PRIMARY KEY ("ID_INTERFACES"));

   /*Tabla que almacena la lista de proyectos, tipo de proyecto y su relación con proyectos del ERP*/
   CREATE TABLE "EBS_UNIFIER"."INT_PROJECT_LIST"
   (	"ID_PROYECTO" NUMBER,
	"PROJECTCODE_U" VARCHAR2(30 BYTE),
	"STATUS_U" VARCHAR2(15 BYTE),
	"PROJECTNAME" VARCHAR2(50 BYTE),
	"PROJECTEBS" VARCHAR2(10 BYTE),
	"TYPE_PROJECT" VARCHAR2(6 BYTE),
	 CONSTRAINT "INT_PROJECT_LIST_EBS_UNIQUE" UNIQUE ("PROJECTEBS"),
   CONSTRAINT "INT_PROJECT_LIST_PK" PRIMARY KEY ("ID_PROYECTO"));

   /*Tabla que almacena el nodo raiz de las estructuras de hoja de costo*/
   CREATE TABLE "EBS_UNIFIER"."INT_ROOTNODE"
   (	"ID_ROOTNODE" NUMBER,
	"SHORTNAME_RN" VARCHAR2(15 BYTE),
	"AUTHCODE_RN" VARCHAR2(10 BYTE),
	"PROJECT_RN" VARCHAR2(50 BYTE),
	"PARENTID_RN" NUMBER,
	 CONSTRAINT "INT_ROOTNODE_CON" UNIQUE ("PROJECT_RN"));

   /*Tabla que almacena el código de estatus de las integraciones, entre las que se incluyen error, advertencia, exito*/
   CREATE TABLE "EBS_UNIFIER"."INT_STATUS_CODE"
   (	"ID_STATUS_CODE" NUMBER,
	"STATUS_CODE" VARCHAR2(10 BYTE),
	"DESCRIPTION" VARCHAR2(100 BYTE),
	"TYPE" VARCHAR2(10 BYTE),
	 CONSTRAINT "INT_STATUS_CODE_PK" PRIMARY KEY ("ID_STATUS_CODE"));

   /*Tabla que almacena el monto actual de las líneas de costo*/
   CREATE TABLE "EBS_UNIFIER"."INT_UPDATE_AMOUNT"
   (	"ID_UPDATE_AMOUNT" NUMBER,
	"PROJECT_EBS" VARCHAR2(30 BYTE),
	"BITEMID_CS" VARCHAR2(2000 BYTE),
	"PROJECT_UNIFIER" VARCHAR2(150 BYTE),
	"RECORD_NO" VARCHAR2(150 BYTE),
	"FLAG" VARCHAR2(3 BYTE),
	"STATUS" VARCHAR2(30 BYTE),
	"AMOUNT" NUMBER,
	"EFFECTIVE_DATE" DATE,
	"TYPE_AMOUNT" VARCHAR2(30 BYTE),
	 CONSTRAINT "INT_UPDATE_AMOUNT_PK" PRIMARY KEY ("ID_UPDATE_AMOUNT"));

  /*Tabla que almacena el log de eventos*/
  CREATE TABLE "EBS_UNIFIER"."LOG_BP_PROCESS"
     (	"ID_LOG_BP_PROCESS" NUMBER,
  	"RESPONSE" VARCHAR2(3 BYTE),
  	"XMLPROCESS" CLOB,
  	"BPNAME" VARCHAR2(150 BYTE),
  	"PROJECT_CODE" VARCHAR2(20 BYTE),
  	"INTERFACE_CODE" NUMBER,
  	"TRANSACTION_EBS" VARCHAR2(150 BYTE),
  	"DATE_TRANSACTION" TIMESTAMP (6),
  	 CONSTRAINT "LOG_BP_PROCESS_PK" PRIMARY KEY ("ID_LOG_BP_PROCESS"));
